### ISSUE TITLE
trufflehog freezes

### ISSUE THREAD

**Issue by Oni-giri** [trunk-io/plugins#346]
Hi,

I downloaded "trufflehog" with the latest update, however it seems to fail when processing the trunk.yaml files.

<img width="821" alt="Capture d’écran 2023-06-30 à 23 11 27" src="https://github.com/trunk-io/plugins/assets/89288375/c1da82e5-3d6b-43f0-8933-395597e7f9b4">

trunk version : 1.11.1

**Comment by TylerJang27** [comment]
Hi! Thanks for reporting this. We've seen this happen a couple of times but have been struggling to track it down. At the very least, we will add a timeout for the linter execution.

A couple quick questions to help us narrow it down:
- If you Ctrl+C and rerun, does it reproduce?
- If you run `trunk daemon shutdown` and then rerun `trunk check --filter=trufflehog`, does it reproduce?

**Comment by aicreatbyme** [comment]
I am facing the same problem and your suggestion work!

**Comment by Oni-giri** [comment]
I ran `trunk upgrade` and it seemed to have fixed the issue. Thanks for the follow-up!
