### ISSUE TITLE
Would be great to see trunk installation available through aqua

### ISSUE THREAD

**Issue by Gowiem** [trunk-io/plugins#358]
## Info

[Aqua](https://aquaproj.github.io/docs/) is a great tool for managing other tools and adding new tools to that registry looks easy overall. It would be great to see trunk in their primary registry. Here is an example of doing so: https://github.com/aquaproj/aqua-registry/pull/13657/files

**Comment by TylerJang27** [comment]
Sorry for the delayed response, this one got lost in our backlog :)

Thanks for suggesting this. I'll follow-up on the included aqua thread for some considerations and potentially some improvements that might help streamline this process!

**Comment by TylerJang27** [comment]
Completed in aqua-registry v4.81.0 and aqua-renovate-config 1.12.0

**Comment by Gowiem** [comment]
Thanks for pushing this forward @TylerJang27 -- I appreciate the help!
