### ISSUE TITLE
Bazel cache Problem

### ISSUE THREAD

**Issue by henrixapp** [trunk-io/plugins#457]
Hi,

I am using trunk in a Bazel project. It works nicely so far, the only issue that I have is that the Bazel calls by trunk constantly invalidate the cache of the Bazel server. That means that I have to recompile every dependency, when I want to run a file (takes about 1 minute, instead of an incremental build taking 10 secs).

Maybe this issue is caused by the env being different for my zsh shell and trunk. Are there any advises on how to fix this?

Best,

Henrik

**Comment by pat-trunk-io** [comment]
Hi Henri,

Are you running with come --config <option> locally or other bazel flag?

Trunk runs bazel query (with default options) as if it was a plain bazel command.
It will pick up things in your .bazelrc, but not what you manually specify on the cli.

**Comment by henrixapp** [comment]
Yes, that could be part of the issue. I usually compile with `-c opt`. Nevertheless, It would be great, if one could control more arguments.

**Comment by pat-trunk-io** [comment]
I submitted the request to the product team.

As far as our setup go, we add this to our bazelrc:

```
# Make a "user.bazelrc" file in the repo root to store personal settings, it's gitignored
try-import %workspace%/user.bazelrc
```

the try-import statement doesn't fail if the file doesn't exist and we add our bazel flags there for local dev. That way it gets picked up by everything that calls bazel.

**Comment by pat-trunk-io** [comment]
Closed as stale
