### ISSUE TITLE
`extra_packages` should append, not replace.

### ISSUE THREAD

**Issue by jun-sheaf** [trunk-io/plugins#489]
It'd be great to have a mechanism which allows extending a set of dependencies for a given tool rather than replacing them. E.g.

Suppose you have

```
      extra_packages:
        - eslint-config-prettier@9.0.0
        - eslint-config-standard-with-typescript@39.0.0
```

for one of your configs. Then

```
      extra_packages:
        - eslint-plugin-lit@1.9.1
```

will replace all of them.

Use case:

 1. Your organization uses ESLint and has a global config.
 2. A local project has specific-requirements requiring another ESLint plugin not defined in the global config.

It's likely that `extra_packages` will always be additive, so it may be worth just making `extra_packages` additive without another mechanism.

**Comment by TylerJang27** [comment]
Hi @jun-sheaf, thanks for using Trunk! We hear your feedback about extra_packages. For the time being, however, we plan to stick to the override syntax for the sake of always being able to replace existing packages. However, there are 2 features that might interest you:
- For eslint specifically, Trunk uses your workspace installation and `node_modules`, so you will usually not want to override packages in your `trunk.yaml`, but rather simply use your existing `package.json` setup. For more details, check out our docs [here](https://docs.trunk.io/check/supported-linters#eslint).
- For other linters, we support additional packages in the enabled section, that I think achieves something very similar to what you requested. Check that our [here](https://docs.trunk.io/check/supported-linters#flake8).

Let me know if that's any help!

**Comment by TylerJang27** [comment]
Hi @jun-sheaf. Any updates on if the above helps out your use case? We're also working on improving our OOTB experience with eslint, with more coming soon.

**Comment by TylerJang27** [comment]
Closing as out of date. More improvements for eslint and packages coming soon!
