### ISSUE TITLE
Document what the `trunk-share-with-everyone` action does

### ISSUE THREAD

**Issue by error9900** [trunk-io/plugins#504]
I can't find anything explaining what the `trunk-share-with-everyone` action does.

**Comment by TylerJang27** [comment]
Hi! `trunk-share-with-everyone` is a built-in [Trunk Action](https://docs.trunk.io/actions) that generates notifications to turn off [single player mode](https://docs.trunk.io/cli/init-in-a-git-repo#single-player-mode). All it does is check for the single player mode status and generate a notification in VSCode, suggesting for users to run `trunk config share`. We get that this can be confusing, and we have plans to improve our documentation around single player mode.

Let me know if that helps!

Also, out of curiosity, how did you come across the `trunk-share-with-everyone` action? It's not something that we advertise as we consider it to be built-in functionality.

**Comment by TylerJang27** [comment]
@error9900 did you encounter this originally while running `trunk actions list` or did you see an error show up in VSCode somewhere?

**Comment by error9900** [comment]
> @error9900 did you encounter this originally while running `trunk actions list` or did you see an error show up in VSCode somewhere?

Yes, `trunk actions list` is how I came across it. I didn't notice any errors related to that action.

And your explanation was sufficient; thanks!
