### ISSUE TITLE
Add test to verify `--filter` option for `trunk check` command in action definitions

### ISSUE THREAD

**Issue by error9900** [trunk-io/plugins#506]
This seems like something that should be relatively easy to catch with a test: https://github.com/trunk-io/plugins/pull/505

**Comment by TylerJang27** [comment]
Adding some more test coverage for all of our actions defined in this repo is on our backlog, and we will definitely keep the trufflehog case in mind. However, this particular issue is a problem of documentation, not of functionality as it pertains to `trufflehog-pre-commit`, which was originally intended as a simple fix requested by a user--not a feature that we necessarily advertise.
