### ISSUE TITLE
Problem with trunk-check-pre-push

### ISSUE THREAD

**Issue by khuongduybui** [trunk-io/plugins#51]
I'm not sure if this is the right repository to report this issue, but when trunk-check-pre-push is enabled, I cannot use `git push --delete <remote> <revspec>` syntax.
```
🕙 11:05:00 quickprice ❯ git push --delete origin uno
✖ Git Error: revspec '(delete)' not found
✖ Push blocked by failing hook 'trunk-check-pre-push'
error: failed to push some refs to '...'
```

**Comment by dapirian** [comment]
👋 hey @khuongduybui issues here are only for reporting issues with trunk plugins - you can report bugs at [slack.trunk.io](https://slack.trunk.io/). I'll close this here and we'll investigate it - feel free to hop on slack to follow for updates! Thanks
