### ISSUE TITLE
Fix codespaces not building

### ISSUE THREAD

**Issue by andreilgeorgescu** [trunk-io/plugins#511]
### Problem
When attempting to create a codespace from this repository's `main` branch, the codespace fails to complete building.

### Steps To Reproduce
1. Open Visual Studio Code (attempted through GitHub UI as well)
2. Run command `Codespaces: Create New Codespace...`
3. Select `trunk-io/plugins`using the official GitHub Repositories extension
4. Wait for `Setting up remote connection: Building codespace...` to enter into a recovery container

### Expected Result
A codespace to be built and usable.

### Actual Result
`Setting up remote connection: Building codespace...` spins indefinitely.

### Suggested Solution
The `.devcontainer.json` file contains the configuration for any built codespaces, so the issue is most likely in this file. The `image` key seems to be using an outdated image of `"mcr.microsoft.com/devcontainers/typescript-node:0-18"` based on its [documentation](https://github.com/devcontainers/images/tree/main/src/typescript-node), so replacing it with a newer image might fix the issue. It is important that semantic versioning is still used along with the same Node and Debian versions so as to not introduce more issues. 

The issue might also be related to the keys `git-lfs` or `onCreateCommand`.

**Comment by andreilgeorgescu** [comment]
After experimenting with a forked copy of this repository, I have concluded that the actual issue is with the `onCreateCommand` key in `.devcontainer.json`. Primarily because `trunk install` takes 7-8 minutes to finish and that seems to result in the build process timing out.

I believe there are three possible solutions to this problem which all involve modifying the [lifecycle script](https://containers.dev/implementors/json_reference/#lifecycle-scripts):
1. Use `postCreateCommand` instead so that `npm ci && trunk install` can run after the codespace has been built. This will still result in just as long of a wait, but at least there won't be a timeout into a recovery container and the user can cancel the installation if desired.
2. Use `updateContentCommand` with [codespace prebuilds](https://docs.github.com/en/codespaces/prebuilding-your-codespaces), which will result in a GitHub Action workflow running on every push to `main` to pre-install this project's extensions and dependencies in an image. This means that a user who wants to create a new codespace won't have to wait for any extension or dependency installation. However, it will cost GitHub Action minutes and codespace usage/storage for your organization.
3. Only use `npm ci` which will mean that trunk will lazily install only what is used by the user. This has the benefit of being quick like the previous option, while not costing your organization anything but can lead to a frustrating experience for users.

I believe the second option, codespace prebuilds, is ideal because it provides the best experience for users with fast load times. In fact, it would be faster than not even including `npm ci && trunk install` because it would also pre-install extensions. However, this will require a repository admin to [configure the prebuild for this repository](https://docs.github.com/en/codespaces/prebuilding-your-codespaces/configuring-prebuilds).

Depending on what solution is decided upon, I can create a pull request when given the go-ahead.

**Comment by laurit17** [comment]
Hi @andreilgeorgescu, apologies for the delayed response-  I appreciate your deep dive on this topic. We are going to take a look at the options you proposed and decide on an appropriate course of action.

**Comment by laurit17** [comment]
Hi @andreilgeorgescu, we are going with option 3) for now and will update you about what we land on.

**Comment by TylerJang27** [comment]
Thanks for the detailed description and options. This should be resolved as of https://github.com/trunk-io/plugins/pull/533, although we may revisit in the future to improve the experience
