### ISSUE TITLE
clang-tidy: broken URLs for help-links, needs only small adaption

### ISSUE THREAD

**Issue by Dominik-K** [trunk-io/plugins#518]
The help-URLs of `clang-tidy` need a `/` instead a `-` at the first occasion in the replacement here:

https://github.com/trunk-io/plugins/blob/6573d6f85e7f172fb6bbc9a1c3b57991348655eb/linters/clang-tidy/plugin.yaml#L53

E.g. for `cppcoreguidelines-pro-type-vararg`:
* current (returns `404 Not Found`): https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-vararg.html
* fix: https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/pro-type-vararg.html

![image](https://github.com/trunk-io/plugins/assets/5795847/b44588a5-aa5e-450b-8f95-3586cc6cb43a)

**Comment by Dominik-K** [comment]
The [URL-format was changed in 2022](https://github.com/llvm/llvm-project/commit/6e566bc5523f743bc34a7e26f050f1f2b4d699a8) and here's the [discussion to it](https://discourse.llvm.org/t/clang-tidy-rfc-use-module-name-as-a-directory-for-organizing-files/62499).

**Comment by TylerJang27** [comment]
Hi Dominik! Thanks for flagging this and all of the detail. We'll look into getting this fixed.
