### ISSUE TITLE
Which options is cspell being run with?

### ISSUE THREAD

**Issue by error9900** [trunk-io/plugins#537]
`trunk check --all --filter cspell` checks 187 files.

`cspell --gitignore .` checks 163 files.
`cspell --gitignore "**"` checks 163 files.

Can't figure out how to get 187 files when running cspell directly, so curious how trunk is running it...

**Comment by TylerJang27** [comment]
Hi @error9900, sorry for the delay in getting to this. Do you have a public repo where you're seeing this? We'd like to unify the behavior so ideally we only run on files that cspell knows it can run on.

With that being said, here's a bit more information:
1. With `--all`, Trunk scans your repo and looks for all files matching the linter's filetype--in this case, [all file extensions](https://github.com/trunk-io/plugins/blob/main/linters/cspell/plugin.yaml#L12)
2. Trunk then runs cspell in batches using the [run command](https://github.com/trunk-io/plugins/blob/main/linters/cspell/plugin.yaml#L18). You can see what this looks like by running `trunk check verbose --filter=cspell <filepath>`

It's possible Trunk is running on some binary or non-text files. We're working on some changes to reduce this scope. If you run `trunk check query --all --filter=cspell`, do you see any particular files that you wouldn't expect to see and that aren't scanned with `cspell --gitignore .`?

**Comment by TylerJang27** [comment]
Hi @error990. Any updates on the behavior you're seeing here?

**Comment by TylerJang27** [comment]
Hi @error9900, checking in one more time here. Any updates on which files Trunk is picking up that cspell is not?

**Comment by error9900** [comment]
Lost track of this. Will give it a try tomorrow!

**Comment by error9900** [comment]
Hmm. So I must have been trying this on my previous work laptop because I don't have cspell installed outside of Trunk on my current computer...

However, when I just ran `trunk check query --all --filter=cspell`, I didn't notice any unexpected files.

**Comment by TylerJang27** [comment]
Gotcha. I'm going to go ahead and close this issue. If you happen to run into it again, please let us know or reach out on our [Community Slack](https://slack.trunk.io/).
