### ISSUE TITLE
.shellcheckrc can be located in home directory

### ISSUE THREAD

**Issue by sheldonhull** [trunk-io/plugins#569]
https://github.com/trunk-io/plugins/blob/bc24c45b5e2502bad62de4e30dc9825c863efa66/linters/shellcheck/plugin.yaml#L41C1-L44C1

This can be set in user home file to override preferences and make them more global.
This doesn't seem to be mapped or respected by trunk.

**Comment by sheldonhull** [comment]
I started on a PR, but didn't see any examples of `direct_configs` showing a `${HOME}` variable that would work cross-platform. Can trunk honor a user config mapping in the home or maybe even `$XDG_CONFIG_HOME` location?

**Comment by TylerJang27** [comment]
Hi @sheldonhull! Trunk's standard approach to this is to respect a linter's own configuration, for example [tflint has its own config order precedence](https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/config.md) (although tflint is a [special case](https://github.com/trunk-io/plugins/issues/565) that we have work planned to fix).

Nevertheless, this should work identically with shellcheck, which I have confirmed locally. If you have a `.shellcheckrc` in your workspace root or `.trunk/configs`, it will apply to the lint run. If you don't, and you have a `~/.shellcheckrc`, that will be loaded. This should work implicitly based on the linter's implementation.

If you're seeing different behavior, please let me know and include a `trunk check --filter=shellcheck --verbose` output.

**Comment by TylerJang27** [comment]
Hi @sheldonhull, were you able to get this working? If you want Trunk to force shellcheck to respect config files in other places via user-overrides on your own machines, there are a couple other options we could pursue if you'd like.

**Comment by sheldonhull** [comment]
I'll close this and come back around if i can't get it to work again. Thanks for the info and I'll give it a shot.
