### ISSUE TITLE
Add markdown-table-prettify plugin

### ISSUE THREAD

**Issue by GustavoAV** [trunk-io/plugins#578]
The [markdown-table-prettify](https://www.npmjs.com/package/markdown-table-prettify) tool formats markdown tables.

I don't know if this type of formatting can be done with **prettier** or any other plugin already listed, but I would really appreciate you guys adding this since it's pretty (pun intended) useful.

**Comment by TylerJang27** [comment]
Hi Gustavo! Thanks for flagging this tool. From my experience, [prettier](https://prettier.io/blog/2017/11/07/1.8.0.html#markdown-support) is capable of formatting markdown pretty well, including markdown tables. Here's a sample of what that looks like in a Trunk output:
![Screenshot 2023-12-07 at 10 09 11 AM](https://github.com/trunk-io/plugins/assets/42743566/2a99aff8-1021-488b-9c56-67c57880e7fc)

We generally favor using prettier and its different [plugins](https://prettier.io/docs/en/plugins) for cases like this; however, configuration can be limited if you wanted to fine-tune this more. [markdown-table-prettify](https://www.npmjs.com/package/markdown-table-prettify) looks relatively straightforward to integrate with Trunk, so we can look into adding it in the next week or so.

**Comment by GustavoAV** [comment]
Great, thank you!

Btw which plugin and config exactly did you use to format tables with prettier?
