### ISSUE TITLE
Support signed commit in `trunk-io/trunk-action/upgrade`

### ISSUE THREAD

**Issue by yu-iskw** [trunk-io/plugins#764]
Let me open the feature request in the repository, since `trunk-io/trunk-action` doesn't allow me to create issues.

Currently, [`trunk-io/trunk-action/upgrade`](https://github.com/trunk-io/trunk-action/tree/main/upgrade) doesn't support [signed commit](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits). If we turn on the setting that commit is required in a GitHub repository, the check doesn't pass. So, it would be great to support signed commit in the action.

<img width="899" alt="image" src="https://github.com/trunk-io/plugins/assets/1523515/cb0c3818-115b-4965-a92e-e1fe1178ae44">

**Comment by TylerJang27** [comment]
Hi @yu-iskw! Thanks for bringing this up! I'll talk to the owning team about making sure that repo supports issues.

In the meantime, we'll look into seeing if we can get signed commits working for that action.

**Comment by TylerJang27** [comment]
@yu-iskw we've released `trunk-io/trunk-action/upgrade@v1.1.14`, which has an option for `signoff`. This should be sufficient for the [DCO](https://github.com/apps/dco) app.

If this is insufficient and you also need the commit to be signed and verified, please let us know and we can look into supporting that.

**Comment by yu-iskw** [comment]
@TylerJang27 Thank you so much. I will give it a try.
