### ISSUE TITLE
Handle empty commit gracefully

### ISSUE THREAD

**Issue by docwhat** [trunk-io/plugins#86]
There is a special ref, `0000000000000000000000000000000000000000`, that is the NULL commit.  It is the first parent commit in any new repository.  

`push.sh` should detect and handle this gracefully, either with `--all` or by just quitting with exit code 0.

Example output from https://github.com/docwhat/gamelist-xml-util/actions/runs/3897696813/jobs/6655627435

```
Run # Run trunk check on push
  # Run trunk check on push
  ${GITHUB_ACTION_PATH}/push.sh
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    TRUNK_TMPDIR: /tmp/tmp.mPY6YzZiZU
    TRUNK_PATH: /tmp/tmp.mPY6YzZiZU/trunk
    TRUNK_CHECK_MODE: push
    MSYS: winsymlinks:nativestrict
    GITHUB_EVENT_AFTER: 2e5cacb1cd3e93e5c1553[40](https://github.com/docwhat/gamelist-xml-util/actions/runs/3897696813/jobs/6655627435#step:3:44)3359772213eb98c83
    GITHUB_EVENT_BEFORE: 0000000000000000000000000000000000000000
    GITHUB_REF_NAME: remove-renovate
    GITHUB_REPOSITORY: docwhat/gamelist-xml-util
    GITHUB_TOKEN: ***
    INPUT_ARGUMENTS: 
    INPUT_LABEL: 
fatal: remote error: upload-pack: not our ref 0000000000000000000000000000000000000000
Error: Process completed with exit code 128.
```

N.B. The NULL commit is also a blob as well. You can see that with renames.  However, that doesn't apply here.

**Comment by det** [comment]
Thanks for the report. We made a new trunk-action release `v1.0.6` (and the `v1` tag) the includes the fix.
